### PR TITLE
Fix runj demo oci-image

### LINKED ISSUE #33: runj demo oci-image generates an image that buildah can't parse
I'm not sure if this is a `buildah` issue or a `runj` issue but i'll start with here:

When generating an image with:
```
$ runj demo oci-image -a arm64 -v 13.1-RELEASE
```
Buildah fails after some time processing with:
```
$ buildah from oci-archive:/tmp/image.tar 
open /var/tmp/oci2475433674/blobs/sha256/3d694e6482e047cd61a4ddbd153307cef6cdf3d4351d84729a3a35d6699db5ed: no such file or directory
```
The `image.tar` generated contains the following files:
```
.
├── blobs
│   ├── 27e61852c31bd49c2364d377534932749138c265d394857c5201180217f49ab5
│   ├── 3d694e6482e047cd61a4ddbd153307cef6cdf3d4351d84729a3a35d6699db5ed
│   └── ccea2ddb5f7be88e12014dbdd424f0d3cce53f7b72f3c6864a1875ce236986b8
├── index.json
└── oci-layout
```
`index.json` (reformatted for clarity) contains:
```
{ "schemaVersion": 2,
  "manifests": [
    { "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:3d694e6482e047cd61a4ddbd153307cef6cdf3d4351d84729a3a35d6699db5ed",
      "size": 350,
      "platform":
        { "architecture": "arm64",
          "os": "freebsd"
        }
    }
  ]
}
```
```
$ file blobs/*
blobs/27e61852c31bd49c2364d377534932749138c265d394857c5201180217f49ab5: gzip compressed data, original size modulo 2^32 958320640
blobs/3d694e6482e047cd61a4ddbd153307cef6cdf3d4351d84729a3a35d6699db5ed: JSON data
blobs/ccea2ddb5f7be88e12014dbdd424f0d3cce53f7b72f3c6864a1875ce236986b8: JSON data
```
`blobs/3d694e6482e047cd61a4ddbd153307cef6cdf3d4351d84729a3a35d6699db5ed` contains:
```
{ "schemaVersion": 2,
  "config":
    { "mediaType": "application/vnd.oci.image.config.v1+json",
      "digest": "sha256:ccea2ddb5f7be88e12014dbdd424f0d3cce53f7b72f3c6864a1875ce236986b8",
      "size": 206
    },
    "layers": [
      { "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
        "digest": "sha256:27e61852c31bd49c2364d377534932749138c265d394857c5201180217f49ab5",
        "size": 280935454
      }
    ]
}
```
`blobs/ccea2ddb5f7be88e12014dbdd424f0d3cce53f7b72f3c6864a1875ce236986b8` contains:
```
{ "author": "runj \u003crunj@sbk.wtf\u003e",
  "architecture": "arm64",
  "os": "freebsd",
  "config": {},
  "rootfs":
    { "type": "layers",
      "diff_ids": ["sha256:7206d787de4f70d6349127a4045078a06577529abc2186ae62d6e42114453575"]
    }
}
```

cc @dfr just in case

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes #33 

See https://github.com/opencontainers/image-spec/blob/bc9c4bd9b2a4ec6f49f956e193f9c699d854507d/image-layout.md#blobs for the spec

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is licensed under the terms found in [the LICENSE file](/LICENSE).

### CODE REVIEW

**Comment by samuelkarp** [comment]
Well that's embarrassing.

@kit-ty-kate I see that you deleted the [pull request template](https://github.com/samuelkarp/runj/blob/main/.github/pull_request_template.md).  Can you affirm that your contribution is licensed under the terms found in [the LICENSE file](https://github.com/samuelkarp/runj/blob/main/LICENSE)?

**Comment by kit-ty-kate** [comment]
Ah, sure. I added the "terms of contribution" section back

**Comment by kit-ty-kate** [comment]
Side note on the template: the link to the LICENSE file does not redirect to the right file. Currently it links to `https://github.com/LICENSE` instead of `https://github.com/samuelkarp/runj/blob/main/LICENSE` as per your comment. Maybe the output is different when you’re the owner of the repository compared to contributers?

**Review by samuelkarp — APPROVED** [review]
Thanks!

**Comment by samuelkarp** [comment]
> Side note on the template: the link to the LICENSE file does not redirect to the right file.

Thanks, fixed in https://github.com/samuelkarp/runj/commit/ec642aa7887be2a4968f20d24b54eed687895a65.

**Pull request merged**
